[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SITE_URL = "https://node-secrets-guide.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200